name: Test Site

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build static site
      run: docker compose --profile build up --build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: static-site
        path: dist/
        if-no-files-found: error
