name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webgltest-env:$(date +%s)
    - name: Build static site
      run: docker run -it --workdir /src -v $(pwd):/src -p 5173:5173 webgltest-env npm run build
