name: Deploy Site

on:
  workflow_run:
    workflows: Test Site
    #branches: main
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: static-site
          path: dist
      - name: "TEST: Display files"
        run: ls -Rla
