name: Deploy Site

on:
  workflow_run:
    workflows: Test Site
    branches: main
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: static-site
          path: dist
      - name: Setup deployment keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Upload static site to server
        run: |
          echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          tar -czf - -C dist . | ssh -J ${{ secrets.DEPLOY_PROXY_USERNAME }}@${{ secrets.DEPLOY_PROXY_HOST }} ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} "rm -rf /srv/jbuelow-com/* && tar -xzf - -C /srv/jbuelow-com"
