name: Deploy Site

on:
  workflow_run:
    workflows: Test Site
    #branches: main
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: static-site
          path: dist
      - name: "TEST: Display files"
        run: ls -Rla